[package]
name = "libreddit"
description = " Alternative private front-end to Reddit"
license = "AGPL-3.0"
repository = "https://github.com/spikecodes/libreddit"
version = "0.2.8"
authors = ["spikecodes <19519553+spikecodes@users.noreply.github.com>"]
edition = "2018"

[dependencies]
base64 = "0.13"
actix-web = { version = "3.3", features = ["rustls"] }
futures = "0.3"
askama = "0.10"
ureq = "2.0"
serde = { version = "1.0", default_features = false, features = ["derive"] }
serde_json = "1.0"
async-recursion = "0.3"
url = "2.2"
regex = "1.4"
time = "0.2"
cached = "0.23.0"
