[package]
name = "libreddit"
description = " Alternative private front-end to Reddit"
license = "AGPL-3.0"
repository = "https://github.com/spikecodes/libreddit"
version = "0.21.3"
authors = ["spikecodes <19519553+spikecodes@users.noreply.github.com>"]
edition = "2021"

[dependencies]
askama = { version = "0.11.0", default-features = false }
async-recursion = "0.3.2"
cached = "0.26.2"
clap = { version = "2.34.0", default-features = false }
regex = "1.5.4"
serde = { version = "1.0.132", features = ["derive"] }
cookie = "0.16.0-rc.1"
futures-lite = "1.12.0"
hyper = { version = "0.14.16", features = ["full"] }
hyper-rustls = "0.23.0"
route-recognizer = "0.3.1"
serde_json = "1.0.73"
tokio = { version = "1.15.0", features = ["full"] }
time = "0.3.5"
url = "2.2.2"
