[package]
name = "libreddit"
description = " Alternative private front-end to Reddit"
license = "AGPL-3.0"
repository = "https://github.com/spikecodes/libreddit"
version = "0.2.9"
authors = ["spikecodes <19519553+spikecodes@users.noreply.github.com>"]
edition = "2018"

[dependencies]
tide = "0.16.0"
async-std = { version = "1.9.0", features = ["attributes"] }
surf = "2.1.0"
base64 = "0.13.0"
cached = "0.23.0"
futures = "0.3.12"
askama = "0.10.5"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
async-recursion = "0.3.2"
regex = "1.4.3"
time = "0.2.25"
