[package]
name = "libreddit"
description = " Alternative private front-end to Reddit"
license = "AGPL-3.0"
repository = "https://github.com/spikecodes/libreddit"
version = "0.1.0"
authors = ["spikecodes <19519553+spikecodes@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.4.0"
askama = "0.9"
serde = "1.0.117"
serde_json = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }
pulldown-cmark = "0.8.0"
chrono = "0.4"

[build-dependencies]
askama = "0.9"